apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "airports.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "airports.name" . }}
    helm.sh/chart: {{ include "airports.chart" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: {{ .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "airports.name" . }}
      app.kubernetes.io/instance: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "airports.name" . }}
        app.kubernetes.io/instance: {{ .Chart.Name }}
      #annotations:
      #  timestamp: "{{ .Values.timestamp }}"

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
        #  livenessProbe:
        #    httpGet:
        #      path: {{ .Values.probes.liveness }}
        #      port: {{ .Values.service.port }}
            #  initialDelaySeconds: 5
            #  periodSeconds: 3
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 10
        #  readinessProbe:
        #    httpGet:
        #      path: {{ .Values.probes.readiness }}
        #      port: {{ .Values.service.port }}
            #  initialDelaySeconds: 5
            #  periodSeconds: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
