# Default values for airports.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: "airports-assembly"
fullnameOverride: "airports-assembly"


image:
  repository: yousefsedky/airports-assembly
  tag: VERSION
  #tag: 1.0.1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

probes:
  liveness: /health/live
  readiness: /health/ready

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: slachtec.local.airports
      paths: [/]

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
