apiVersion: v1
kind: Service
metadata:
  name: {{ include "countries.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "countries.name" . }}
    helm.sh/chart: {{ include "countries.chart" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "countries.name" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
