apiVersion: v1
kind: Service
metadata:
  name: {{ include "airports.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "airports.name" . }}
    helm.sh/chart: {{ include "airports.chart" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "airports.name" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
